apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- digest: sha256:08b9c1629c074e68716f9153b2260166aeebb0baf580c7a48d780dfb68638e71
  name: dotnet-6.0
  newName: quay.io/narendragomte/sample-app
