apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- digest: sha256:6e609ba60f4a0990d90fd452c5738c3ec3f2cae85c58986389842650db92d560
  name: dotnet-6.0
  newName: quay.io/narendragomte/sample-app
