apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- digest: sha256:1afef6751128d75918375da3e15592ed89d83cc8ec9b08fa9c19a1cf96a99727
  name: dotnet-6.0
  newName: quay.io/narendragomte/sample-app
